-- ============================================================================
--  SmilesCars — Supabase schema for the API in /api + /lib
--  Run once in the Supabase SQL editor (SQL Editor -> New query -> Run).
--
--  SAFE TO RE-RUN. Every statement is additive and idempotent:
--    * CREATE TABLE IF NOT EXISTS   — never touches a table that already exists
--    * ADD COLUMN IF NOT EXISTS     — never changes an existing column's type
--    * no DROP, no DELETE, no UPDATE of business data
--
--  Column types are dictated by the API's write coercion (lib/core.js): a
--  column listed there as numeric/timestamp receives NULL when the app clears
--  it; everything else stays text so a blank "" is always a legal value.
--
--  After running this, check the result with:  GET /api?action=health
-- ============================================================================

-- ── Fleet ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fleet (
  plate             text PRIMARY KEY,
  type              text,
  location          text,
  status            text,
  current_client    text,
  client_phone      text,
  booked_from       timestamp,
  return_date       timestamp,
  remarks           text,
  fuel_out          text,
  amount            numeric,
  currency          text,
  garage            text,
  payment_status    text,
  amount_paid       numeric,
  police_fine_out   numeric,
  parking_fine_out  numeric,
  km_out            text,
  driver            text,
  reg_card_url      text,
  photos_url        text,
  checked_out_by    text,
  booking_type      text
);

ALTER TABLE fleet ADD COLUMN IF NOT EXISTS checked_out_by   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS booking_type     text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS reg_card_url     text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS photos_url       text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS police_fine_out  numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS parking_fine_out numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS km_out           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS driver           text;

-- ── History ─────────────────────────────────────────────────────────────────
-- `id` gives the append-only log a stable newest-first order (the app used to
-- rely on sheet row position).
CREATE TABLE IF NOT EXISTS history (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp      timestamp,
  plate          text,
  type           text,
  action         text,
  client         text,
  client_phone   text,
  booked_from    timestamp,
  return_date    timestamp,
  location       text,
  remarks        text,
  staff_name     text,
  fuel_out       text,
  fuel_in        text,
  amount         numeric,
  currency       text,
  police_fine    numeric,
  parking_fine   text,
  garage         text,
  payment_status text,
  amount_paid    numeric,
  km_out         text,
  km_in          text,
  driver         text
);

-- If history came from the sheet export without a surrogate key, add one. On a
-- non-empty table Postgres backfills it in the table's existing physical order,
-- which for an append-only log is insertion order.
ALTER TABLE history ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS history_plate_idx      ON history (lower(btrim(plate)));
CREATE INDEX IF NOT EXISTS history_staff_name_idx ON history (lower(btrim(staff_name)));

-- ── Config (staff, locations, garages, drivers, fuel access) ────────────────
CREATE TABLE IF NOT EXISTS config (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type     text,
  value    text,
  password text,
  role     text,
  active   text
);

-- Staff activation, used by verifyStaff / getStaffList / setStaffActive.
ALTER TABLE config ADD COLUMN IF NOT EXISTS active   text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS role     text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS id       bigint GENERATED BY DEFAULT AS IDENTITY;

-- Blank counts as active in code; this just makes it explicit.
UPDATE config SET active = 'TRUE' WHERE type = 'Staff' AND (active IS NULL OR active = '');

-- ── Settings ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
  key   text PRIMARY KEY,
  value boolean
);

-- ── Sold ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sold (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp  timestamp,
  plate      text,
  type       text,
  remarks    text,
  staff_name text
);
ALTER TABLE sold ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- ── Sub-Hire ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sub_hire (
  id                   text PRIMARY KEY,
  status               text,
  supplier_name        text,
  supplier_contact     text,
  vehicle_description  text,
  client               text,
  client_phone         text,
  booked_from          timestamp,
  return_date          timestamp,
  actual_return        timestamp,
  location             text,
  fuel_out             text,
  fuel_in              text,
  amount               numeric,
  currency             text,
  payment_status       text,
  amount_paid          numeric,
  supplier_amount      numeric,
  supplier_currency    text,
  supplier_pay_status  text,
  supplier_amount_paid numeric,
  police_fine          numeric,
  parking_fine         numeric,
  remarks              text,
  staff_name           text,
  timestamp            timestamp,
  plate_no             text
);
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS plate_no text;

-- ── Fuel ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fuel (
  ref_no        text PRIMARY KEY,
  timestamp     timestamp,
  date          timestamp,
  plate         text,
  vehicle_type  text,
  product       text,
  amount_tsh    text,
  litres        text,
  authorised_by text,
  submitted_by  text,
  linked_client text,
  current_km    numeric
);
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS current_km    numeric;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS linked_client text;

CREATE INDEX IF NOT EXISTS fuel_plate_idx ON fuel (lower(btrim(plate)));

-- ── Reservations ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reservations (
  id           text PRIMARY KEY,
  plate        text,
  car_type     text,
  client_name  text,
  phone        text,
  pickup_date  timestamp,
  return_date  timestamp,
  pick_up_from text,
  remarks      text,
  staff_name   text,
  timestamp    timestamp
);

-- ── Blacklist ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS blacklist (
  id                text PRIMARY KEY,
  name              text,
  phone             text,
  license_no        text,
  license_image_url text,
  file_id           text,
  added_by          text,
  timestamp         timestamp
);
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS file_id text;

-- ============================================================================
--  Tables that replace Google Drive / Script Properties
-- ============================================================================

-- ── Stored files: licence photos, signatures, agreement PDFs, backups ───────
-- Served back to the browser at /api?action=file&id=<id>.
CREATE TABLE IF NOT EXISTS files (
  id         text PRIMARY KEY,
  kind       text,            -- blacklist | signature | staff-signature | agreement | backup
  filename   text,
  mime_type  text,
  size_bytes integer,
  data       bytea NOT NULL,
  created_at timestamp,
  created_by text
);
CREATE INDEX IF NOT EXISTS files_kind_idx ON files (kind);

-- ── Rental agreements (was: the "Agreements" sheet + a Drive folder) ────────
CREATE TABLE IF NOT EXISTS agreements (
  ref        text,
  plate      text,
  client     text,
  staff_name text,
  timestamp  timestamp,
  drive_url  text,           -- kept as the column name so pre-migration rows still read
  file_id    text
);
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS file_id   text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS drive_url text;
CREATE INDEX IF NOT EXISTS agreements_ref_idx ON agreements (ref);

-- ── Client signature hand-off (was: Script Properties, 24h TTL) ─────────────
CREATE TABLE IF NOT EXISTS signature_tokens (
  token      text PRIMARY KEY,
  file_id    text,
  url        text,
  created_at timestamp
);

-- ── Staff signatures, one per staff member (was: Script Properties) ─────────
CREATE TABLE IF NOT EXISTS staff_signatures (
  staff_name text PRIMARY KEY,   -- stored lowercased
  file_id    text,
  url        text,
  updated_at timestamp
);

-- ── Export audit log (was: the "ExportLog" sheet) ───────────────────────────
CREATE TABLE IF NOT EXISTS export_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp   timestamp,
  staff_name  text,
  role        text,
  export_type text,
  row_count   integer,
  filters     text
);
