-- ============================================================================
--  SmilesCars — Supabase schema for the API in /api + /lib
--  Run in the Supabase SQL editor (SQL Editor -> New query -> Run).
--
--  SAFE TO RE-RUN. Every statement is additive and idempotent:
--    * CREATE TABLE IF NOT EXISTS   — never touches a table that already exists
--    * ADD COLUMN IF NOT EXISTS     — never changes an existing column's type
--    * no DROP, no DELETE, no UPDATE of business data
--
--  It runs in three phases:
--    1. create any table that is missing
--    2. reconcile columns — every column the API touches, on every table, so a
--       table that arrived from the sheet export with a different set of
--       columns gets brought up to date
--    3. indexes
--
--  Column types are dictated by the API's write coercion (lib/core.js): a
--  column listed there as numeric/timestamp receives NULL when the app clears
--  it; everything else stays text so a blank "" is always a legal value.
--
--  Check the result with:  npm run db:check    (or GET /api?action=health)
-- ============================================================================


-- ============================================================================
--  PHASE 1 — tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS fleet (
  plate             text PRIMARY KEY,
  type              text,
  location          text,
  status            text,
  current_client    text,
  client_phone      text,
  booked_from       timestamp,
  return_date       timestamp,
  remarks           text,
  fuel_out          text,
  amount            numeric,
  currency          text,
  garage            text,
  payment_status    text,
  amount_paid       numeric,
  police_fine_out   numeric,
  parking_fine_out  numeric,
  km_out            text,
  driver            text,
  reg_card_url      text,
  photos_url        text,
  checked_out_by    text,
  booking_type      text
);

-- `id` gives the append-only log a stable newest-first order (the app used to
-- rely on sheet row position).
CREATE TABLE IF NOT EXISTS history (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp      timestamp,
  plate          text,
  type           text,
  action         text,
  client         text,
  client_phone   text,
  booked_from    timestamp,
  return_date    timestamp,
  location       text,
  remarks        text,
  staff_name     text,
  fuel_out       text,
  fuel_in        text,
  amount         numeric,
  currency       text,
  police_fine    numeric,
  parking_fine   text,
  garage         text,
  payment_status text,
  amount_paid    numeric,
  km_out         text,
  km_in          text,
  driver         text
);

-- Staff, locations, garages, drivers, fuel access.
CREATE TABLE IF NOT EXISTS config (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type     text,
  value    text,
  password text,
  role     text,
  active   text
);

CREATE TABLE IF NOT EXISTS settings (
  key   text PRIMARY KEY,
  value boolean
);

CREATE TABLE IF NOT EXISTS sold (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp  timestamp,
  plate      text,
  type       text,
  remarks    text,
  staff_name text
);

CREATE TABLE IF NOT EXISTS sub_hire (
  id                   text PRIMARY KEY,
  status               text,
  supplier_name        text,
  supplier_contact     text,
  vehicle_description  text,
  client               text,
  client_phone         text,
  booked_from          timestamp,
  return_date          timestamp,
  actual_return        timestamp,
  location             text,
  fuel_out             text,
  fuel_in              text,
  amount               numeric,
  currency             text,
  payment_status       text,
  amount_paid          numeric,
  supplier_amount      numeric,
  supplier_currency    text,
  supplier_pay_status  text,
  supplier_amount_paid numeric,
  police_fine          numeric,
  parking_fine         numeric,
  remarks              text,
  staff_name           text,
  timestamp            timestamp,
  plate_no             text
);

CREATE TABLE IF NOT EXISTS fuel (
  ref_no        text PRIMARY KEY,
  timestamp     timestamp,
  date          timestamp,
  plate         text,
  vehicle_type  text,
  product       text,
  amount_tsh    text,
  litres        text,
  authorised_by text,
  submitted_by  text,
  linked_client text,
  current_km    numeric
);

CREATE TABLE IF NOT EXISTS reservations (
  id           text PRIMARY KEY,
  plate        text,
  car_type     text,
  client_name  text,
  phone        text,
  pickup_date  timestamp,
  return_date  timestamp,
  pick_up_from text,
  remarks      text,
  staff_name   text,
  timestamp    timestamp
);

CREATE TABLE IF NOT EXISTS blacklist (
  id                text PRIMARY KEY,
  name              text,
  phone             text,
  license_no        text,
  license_image_url text,
  file_id           text,
  added_by          text,
  timestamp         timestamp
);

-- ── Tables that replace Google Drive / Script Properties ────────────────────

-- Licence photos, signatures, agreement PDFs and backups, served back to the
-- browser at /api?action=file&id=<id>.
CREATE TABLE IF NOT EXISTS files (
  id         text PRIMARY KEY,
  kind       text,            -- blacklist | signature | staff-signature | agreement | backup
  filename   text,
  mime_type  text,
  size_bytes integer,
  data       bytea NOT NULL,
  created_at timestamp,
  created_by text
);

-- Was: the "Agreements" sheet + a Drive folder.
CREATE TABLE IF NOT EXISTS agreements (
  ref        text,
  plate      text,
  client     text,
  staff_name text,
  timestamp  timestamp,
  drive_url  text,           -- kept as the column name so pre-migration rows still read
  file_id    text
);

-- Client signature hand-off. Was: Script Properties, 24h TTL.
CREATE TABLE IF NOT EXISTS signature_tokens (
  token      text PRIMARY KEY,
  file_id    text,
  url        text,
  created_at timestamp
);

-- One per staff member. Was: Script Properties.
CREATE TABLE IF NOT EXISTS staff_signatures (
  staff_name text PRIMARY KEY,   -- stored lowercased
  file_id    text,
  url        text,
  updated_at timestamp
);

-- Was: the "ExportLog" sheet.
CREATE TABLE IF NOT EXISTS export_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp   timestamp,
  staff_name  text,
  role        text,
  export_type text,
  row_count   integer,
  filters     text
);


-- ============================================================================
--  PHASE 2 — column reconciliation
--
--  Every column the API reads or writes, for every table. A table created
--  above already has them all and each statement is a no-op; a table that came
--  from the sheet export gets whatever it is missing. Types are never altered,
--  so an existing column keeps whatever type it already has.
-- ============================================================================

-- ── Renames first ───────────────────────────────────────────────────────────
-- The Agreements sheet headed this column "Staff" (History used "Staff Name"),
-- so the export produced `staff`. Rename rather than add, or the staff names on
-- existing agreement rows are stranded in a column nothing reads.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='agreements' AND column_name='staff')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='agreements' AND column_name='staff_name')
  THEN
    ALTER TABLE agreements RENAME COLUMN staff TO staff_name;
  END IF;
END $$;

-- ── Surrogate keys ──────────────────────────────────────────────────────────
-- On a non-empty table Postgres backfills an identity column in the table's
-- existing physical order, which for an append-only log is insertion order.
ALTER TABLE history ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE config  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE sold    ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- ── Fleet ───────────────────────────────────────────────────────────────────
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS plate            text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS type             text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS location         text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS status           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS current_client   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS client_phone     text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS booked_from      timestamp;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS return_date      timestamp;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS remarks          text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS fuel_out         text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS amount           numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS currency         text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS garage           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS payment_status   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS amount_paid      numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS police_fine_out  numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS parking_fine_out numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS km_out           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS driver           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS reg_card_url     text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS photos_url       text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS checked_out_by   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS booking_type     text;

-- ── History ─────────────────────────────────────────────────────────────────
ALTER TABLE history ADD COLUMN IF NOT EXISTS timestamp      timestamp;
ALTER TABLE history ADD COLUMN IF NOT EXISTS plate          text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS type           text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS action         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS client         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS client_phone   text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS booked_from    timestamp;
ALTER TABLE history ADD COLUMN IF NOT EXISTS return_date    timestamp;
ALTER TABLE history ADD COLUMN IF NOT EXISTS location       text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS remarks        text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS staff_name     text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS fuel_out       text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS fuel_in        text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS amount         numeric;
ALTER TABLE history ADD COLUMN IF NOT EXISTS currency       text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS police_fine    numeric;
ALTER TABLE history ADD COLUMN IF NOT EXISTS parking_fine   text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS garage         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS payment_status text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS amount_paid    numeric;
ALTER TABLE history ADD COLUMN IF NOT EXISTS km_out         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS km_in          text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS driver         text;

-- ── Config ──────────────────────────────────────────────────────────────────
ALTER TABLE config ADD COLUMN IF NOT EXISTS type     text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS value    text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS role     text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS active   text;

-- ── Settings ────────────────────────────────────────────────────────────────
ALTER TABLE settings ADD COLUMN IF NOT EXISTS key   text;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS value boolean;

-- ── Sold ────────────────────────────────────────────────────────────────────
ALTER TABLE sold ADD COLUMN IF NOT EXISTS timestamp  timestamp;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS plate      text;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS type       text;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS remarks    text;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS staff_name text;

-- ── Sub-Hire ────────────────────────────────────────────────────────────────
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS id                   text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS status               text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_name        text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_contact     text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS vehicle_description  text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS client               text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS client_phone         text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS booked_from          timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS return_date          timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS actual_return        timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS location             text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS fuel_out             text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS fuel_in              text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS amount               numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS currency             text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS payment_status       text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS amount_paid          numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_amount      numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_currency    text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_pay_status  text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_amount_paid numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS police_fine          numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS parking_fine         numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS remarks              text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS staff_name           text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS timestamp            timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS plate_no             text;

-- ── Fuel ────────────────────────────────────────────────────────────────────
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS ref_no        text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS timestamp     timestamp;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS date          timestamp;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS plate         text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS vehicle_type  text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS product       text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS amount_tsh    text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS litres        text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS authorised_by text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS submitted_by  text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS linked_client text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS current_km    numeric;

-- ── Reservations ────────────────────────────────────────────────────────────
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS id           text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS plate        text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS car_type     text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS client_name  text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS phone        text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS pickup_date  timestamp;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS return_date  timestamp;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS pick_up_from text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS remarks      text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS staff_name   text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS timestamp    timestamp;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS booking_type  text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS drop_off_to   text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS transfer_date timestamp;
UPDATE reservations SET booking_type = 'Rental' WHERE booking_type IS NULL;

-- ── Blacklist ───────────────────────────────────────────────────────────────
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS id                text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS name              text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS phone             text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS license_no        text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS license_image_url text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS file_id           text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS added_by          text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS timestamp         timestamp;

-- ── Files ───────────────────────────────────────────────────────────────────
ALTER TABLE files ADD COLUMN IF NOT EXISTS id         text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS kind       text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS filename   text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS mime_type  text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS size_bytes integer;
ALTER TABLE files ADD COLUMN IF NOT EXISTS data       bytea;
ALTER TABLE files ADD COLUMN IF NOT EXISTS created_at timestamp;
ALTER TABLE files ADD COLUMN IF NOT EXISTS created_by text;

-- ── Agreements ──────────────────────────────────────────────────────────────
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS ref        text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS plate      text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS client     text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS staff_name text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS timestamp  timestamp;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS drive_url  text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS file_id    text;

-- ── Signature tokens ────────────────────────────────────────────────────────
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS token      text;
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS file_id    text;
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS url        text;
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS created_at timestamp;

-- ── Staff signatures ────────────────────────────────────────────────────────
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS staff_name text;
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS file_id    text;
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS url        text;
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS updated_at timestamp;

-- ── Export log ──────────────────────────────────────────────────────────────
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS timestamp   timestamp;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS staff_name  text;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS role        text;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS export_type text;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS row_count   integer;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS filters     text;

-- Blank counts as active in code; this just makes it explicit.
UPDATE config SET active = 'TRUE' WHERE type = 'Staff' AND (active IS NULL OR active = '');


-- ============================================================================
--  PHASE 3 — indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS history_plate_idx      ON history (lower(btrim(plate)));
CREATE INDEX IF NOT EXISTS history_staff_name_idx ON history (lower(btrim(staff_name)));
CREATE INDEX IF NOT EXISTS fuel_plate_idx         ON fuel (lower(btrim(plate)));
CREATE INDEX IF NOT EXISTS files_kind_idx         ON files (kind);
CREATE INDEX IF NOT EXISTS agreements_ref_idx     ON agreements (ref);

-- ============================================================================
--  Leads / Maintenance module additions
-- ============================================================================

CREATE TABLE IF NOT EXISTS maintenance_log (
  id                text PRIMARY KEY,
  plate             text NOT NULL,
  opened_by         text,
  assigned_mechanic text,
  issue_description text,
  status            text DEFAULT 'Queued',
  date_opened       timestamp DEFAULT now(),
  date_closed       timestamp,
  odometer          text,
  parts_cost        numeric DEFAULT 0,
  labor_cost        numeric DEFAULT 0,
  total_cost        numeric DEFAULT 0,
  notes             text,
  created_at        timestamp DEFAULT now(),
  updated_at        timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_log_plate  ON maintenance_log(plate);
CREATE INDEX IF NOT EXISTS idx_maintenance_log_status ON maintenance_log(status);

-- Human-facing sequential reference number, e.g. SC/GAR/2026/08/0001.
-- id stays as the internal PK (MX-XXXXXXXX); ref_no is what staff see/write down.
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS ref_no text UNIQUE;

-- Job card line items — one row per part, linked to a work order.
-- No labor field: line items ARE the cost breakdown (labor isn't tracked).
CREATE TABLE IF NOT EXISTS maintenance_items (
  id             text PRIMARY KEY,
  work_order_id  text NOT NULL REFERENCES maintenance_log(id) ON DELETE CASCADE,
  item_name      text NOT NULL,
  quantity       numeric DEFAULT 1,
  unit_cost      numeric DEFAULT 0,
  line_total     numeric DEFAULT 0,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_items_wo ON maintenance_items(work_order_id);

-- Running update log for a work order (timestamped entries, not a single
-- overwritable notes field) — visible history of everything reported as
-- the job progressed.
CREATE TABLE IF NOT EXISTS maintenance_updates (
  id             text PRIMARY KEY,
  work_order_id  text NOT NULL REFERENCES maintenance_log(id) ON DELETE CASCADE,
  author         text,
  message        text NOT NULL,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_updates_wo ON maintenance_updates(work_order_id);

-- Phase 4 scheduling: Garage Manager manually sets both of these on the
-- Maintenance page. No auto-estimation from Fuel/Maintenance readings —
-- deliberately kept simple and explicit.
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS next_service_due_km numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS last_known_odometer numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS odometer_updated_at timestamp;

-- Leads pipeline (Kanban board): New / Contacted / Negotiating / Outcome.
-- Sourced from WhatsApp automation (via /api endpoint, not direct table
-- access) and manual entry. outcome ('Won'/'Lost') is a sub-state of the
-- Outcome stage, not a separate stage.
CREATE TABLE IF NOT EXISTS leads (
  id                       text PRIMARY KEY,
  client_name              text NOT NULL,
  phone                    text NOT NULL,
  booking_type             text DEFAULT 'Rental',
  pick_up_location         text,
  vehicle                  text,
  pickup_date              timestamp,
  return_date              timestamp,
  source                   text DEFAULT 'WhatsApp',
  stage                    text DEFAULT 'New',
  outcome                  text,
  assigned_staff           text,
  notes                    text,
  lost_reason              text,
  last_contact_date        timestamp,
  converted_reservation_id text,
  created_at               timestamp DEFAULT now(),
  updated_at               timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leads_stage ON leads(stage);

-- Reservations: two-part pickup/dropoff location (city + specific location),
-- and cancellation (kept as a record, not deleted -- status + reason).
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS pick_up_city  text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS drop_off_city text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS status             text DEFAULT 'Active';
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS cancel_reason      text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS cancelled_by       text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS cancelled_at       timestamp;
UPDATE reservations SET status = 'Active' WHERE status IS NULL;

-- Garage: vendors/suppliers and parts inventory with real stock tracking.
CREATE TABLE IF NOT EXISTS vendors (
  id               text PRIMARY KEY,
  name             text NOT NULL,
  contact_person   text,
  phone            text,
  location         text,
  categories       text,
  payment_terms    text,
  notes            text,
  active           text DEFAULT 'TRUE',
  created_at       timestamp DEFAULT now(),
  updated_at       timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parts (
  id                 text PRIMARY KEY,
  name               text NOT NULL,
  category           text,
  vendor_id          text REFERENCES vendors(id) ON DELETE SET NULL,
  unit_cost          numeric DEFAULT 0,
  quantity_on_hand   numeric DEFAULT 0,
  reorder_threshold  numeric DEFAULT 0,
  notes              text,
  active             text DEFAULT 'TRUE',
  created_at         timestamp DEFAULT now(),
  updated_at         timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_parts_vendor ON parts(vendor_id);
CREATE INDEX IF NOT EXISTS idx_parts_category ON parts(category);

-- Links a job card item back to the part it was drawn from (nullable --
-- free-text items have no part_id) so stock decrements are traceable.
ALTER TABLE maintenance_items ADD COLUMN IF NOT EXISTS part_id text REFERENCES parts(id) ON DELETE SET NULL;

-- Vendors: distinguish Parts Supplier / Service Provider / Both.
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS vendor_type text DEFAULT 'Parts Supplier';
UPDATE vendors SET vendor_type = 'Parts Supplier' WHERE vendor_type IS NULL;

-- Work order: service location (Internal office/garage vs External vendor)
-- and an optional flat cost for jobs without an itemized parts breakdown.
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS service_location_type text DEFAULT 'Internal';
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS internal_location      text;
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS external_vendor_id     text REFERENCES vendors(id) ON DELETE SET NULL;
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS flat_cost              numeric;
UPDATE maintenance_log SET service_location_type = 'Internal' WHERE service_location_type IS NULL;

-- Recurring service templates: reusable definitions (e.g. "Oil Change every
-- 5,000km / 3 months") with an optional standard parts list, assignable to
-- multiple cars independently.
CREATE TABLE IF NOT EXISTS service_templates (
  id                 text PRIMARY KEY,
  name               text NOT NULL,
  description        text,
  interval_km        numeric,
  interval_months    numeric,
  active             text DEFAULT 'TRUE',
  created_at         timestamp DEFAULT now(),
  updated_at         timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS service_template_parts (
  id             text PRIMARY KEY,
  template_id    text NOT NULL REFERENCES service_templates(id) ON DELETE CASCADE,
  part_id        text NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
  quantity       numeric DEFAULT 1,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_template_parts_template ON service_template_parts(template_id);

CREATE TABLE IF NOT EXISTS car_service_assignments (
  id             text PRIMARY KEY,
  plate          text NOT NULL,
  template_id    text NOT NULL REFERENCES service_templates(id) ON DELETE CASCADE,
  last_done_km   numeric,
  last_done_date timestamp,
  active         text DEFAULT 'TRUE',
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now(),
  UNIQUE(plate, template_id)
);

CREATE INDEX IF NOT EXISTS idx_car_service_plate ON car_service_assignments(plate);
CREATE INDEX IF NOT EXISTS idx_car_service_template ON car_service_assignments(template_id);

ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS service_assignment_id text REFERENCES car_service_assignments(id) ON DELETE SET NULL;

-- Checklist/Inspection templates: reusable item lists (e.g. "Pre-Rental
-- Inspection"), filled out either against a work order or standalone
-- against a car directly.
CREATE TABLE IF NOT EXISTS checklist_templates (
  id             text PRIMARY KEY,
  name           text NOT NULL,
  description    text,
  active         text DEFAULT 'TRUE',
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS checklist_template_items (
  id             text PRIMARY KEY,
  template_id    text NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE,
  label          text NOT NULL,
  sort_order     numeric DEFAULT 0,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_checklist_template_items_template ON checklist_template_items(template_id);

CREATE TABLE IF NOT EXISTS checklist_instances (
  id             text PRIMARY KEY,
  template_id    text NOT NULL REFERENCES checklist_templates(id) ON DELETE RESTRICT,
  plate          text NOT NULL,
  work_order_id  text REFERENCES maintenance_log(id) ON DELETE SET NULL,
  completed_by   text,
  has_failure    text DEFAULT 'FALSE',
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_checklist_instances_plate ON checklist_instances(plate);
CREATE INDEX IF NOT EXISTS idx_checklist_instances_wo ON checklist_instances(work_order_id);
CREATE INDEX IF NOT EXISTS idx_checklist_instances_failure ON checklist_instances(has_failure);

CREATE TABLE IF NOT EXISTS checklist_instance_items (
  id             text PRIMARY KEY,
  instance_id    text NOT NULL REFERENCES checklist_instances(id) ON DELETE CASCADE,
  label          text NOT NULL,
  state          text DEFAULT 'Good',
  note           text,
  sort_order     numeric DEFAULT 0,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_checklist_instance_items_instance ON checklist_instance_items(instance_id);

-- Vendor categories: master list (extensible by Admin/Garage Manager) +
-- many-to-many links, so a vendor can carry multiple categories
-- (e.g. Tyres + Parts) separate from the coarser vendor_type field.
CREATE TABLE IF NOT EXISTS vendor_categories (
  id         text PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  created_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vendor_category_links (
  id           text PRIMARY KEY,
  vendor_id    text NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
  category_id  text NOT NULL REFERENCES vendor_categories(id) ON DELETE CASCADE,
  UNIQUE(vendor_id, category_id)
);

CREATE INDEX IF NOT EXISTS idx_vendor_category_links_vendor ON vendor_category_links(vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_category_links_category ON vendor_category_links(category_id);

INSERT INTO vendor_categories (id, name) VALUES
  ('VC-GARAGE',    'Garage'),
  ('VC-PARTS',     'Parts'),
  ('VC-TYRES',     'Tyres'),
  ('VC-BATTERY',   'Battery'),
  ('VC-BODYPAINT', 'Body & Paint'),
  ('VC-ELECTRICAL','Electrical'),
  ('VC-ACCOOLING', 'AC / Cooling'),
  ('VC-GLASS',     'Glass / Windscreen'),
  ('VC-TOWING',    'Towing'),
  ('VC-FUEL',      'Fuel'),
  ('VC-UPHOLSTERY','Upholstery / Interior'),
  ('VC-CARWASH',   'Car Wash / Detailing')
ON CONFLICT (name) DO NOTHING;

-- Customer Jobs: SmilesCars Garage servicing OUTSIDE customers' cars, a
-- real business line separate from fleet maintenance. Not tied to any
-- Fleet plate; kept fully separate from maintenance_log so fleet cost
-- tracking and Analytics never mix with customer revenue.
CREATE TABLE IF NOT EXISTS customer_jobs (
  id                 text PRIMARY KEY,
  ref_no             text UNIQUE,
  customer_name      text NOT NULL,
  customer_phone     text NOT NULL,
  plate              text NOT NULL,
  car_description    text,
  assigned_mechanic  text,
  issue_description  text,
  status             text DEFAULT 'Queued',
  odometer           text,
  notes              text,
  total_cost         numeric DEFAULT 0,
  price_charged      numeric DEFAULT 0,
  payment_status     text DEFAULT 'Unpaid',
  amount_paid        numeric DEFAULT 0,
  opened_by          text,
  date_opened        timestamp DEFAULT now(),
  date_closed        timestamp,
  created_at         timestamp DEFAULT now(),
  updated_at         timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_jobs_status ON customer_jobs(status);
CREATE INDEX IF NOT EXISTS idx_customer_jobs_plate ON customer_jobs(plate);

CREATE TABLE IF NOT EXISTS customer_job_items (
  id             text PRIMARY KEY,
  job_id         text NOT NULL REFERENCES customer_jobs(id) ON DELETE CASCADE,
  item_name      text NOT NULL,
  quantity       numeric DEFAULT 1,
  unit_cost      numeric DEFAULT 0,
  line_total     numeric DEFAULT 0,
  part_id        text REFERENCES parts(id) ON DELETE SET NULL,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_job_items_job ON customer_job_items(job_id);

CREATE TABLE IF NOT EXISTS customer_job_updates (
  id             text PRIMARY KEY,
  job_id         text NOT NULL REFERENCES customer_jobs(id) ON DELETE CASCADE,
  author         text,
  message        text NOT NULL,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_job_updates_job ON customer_job_updates(job_id);

-- "From Supplier" job card items can optionally link to a real vendor.
ALTER TABLE maintenance_items ADD COLUMN IF NOT EXISTS supplier_vendor_id text REFERENCES vendors(id) ON DELETE SET NULL;
ALTER TABLE customer_job_items ADD COLUMN IF NOT EXISTS supplier_vendor_id text REFERENCES vendors(id) ON DELETE SET NULL;

-- Free-text branch/location names per supplier (not tied to real Fleet
-- locations -- just which of that supplier's own branches).
CREATE TABLE IF NOT EXISTS vendor_locations (
  id          text PRIMARY KEY,
  vendor_id   text NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
  name        text NOT NULL,
  created_at  timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vendor_locations_vendor ON vendor_locations(vendor_id);

-- Which of the supplier's branches an item/job/work order was from, copied
-- at selection time (not a foreign key) so history stays intact even if
-- the supplier's location list changes later.
ALTER TABLE maintenance_items ADD COLUMN IF NOT EXISTS supplier_location text;
ALTER TABLE customer_job_items ADD COLUMN IF NOT EXISTS supplier_location text;
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS external_vendor_location text;

-- Staff notifications: persisted, per-recipient, read/unread. recipient is
-- either a staff name (individual) or a role string like 'Garage Manager'
-- / 'Admin' (broadcast to everyone with that role). dedupe_key prevents
-- the same underlying event (e.g. a scheduled reminder re-running) from
-- creating duplicate notifications.
CREATE TABLE IF NOT EXISTS notifications (
  id           text PRIMARY KEY,
  recipient    text NOT NULL,
  type         text NOT NULL,
  title        text NOT NULL,
  message      text,
  link_path    text,
  read         text DEFAULT 'FALSE',
  read_at      timestamp,
  dedupe_key   text,
  created_at   timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient, read, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_dedupe ON notifications(dedupe_key) WHERE dedupe_key IS NOT NULL;

-- Per-staff setting: receive a reminder for EVERY reservation (not just
-- their own) 24h before pickup.
ALTER TABLE config ADD COLUMN IF NOT EXISTS receives_all_reservation_reminders text DEFAULT 'FALSE';

-- Push subscriptions: one row per device a staff member has enabled push
-- on (multi-device supported -- phone + desktop, etc.). endpoint is
-- unique per browser/device.
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id           text PRIMARY KEY,
  staff_name   text NOT NULL,
  endpoint     text NOT NULL UNIQUE,
  p256dh       text NOT NULL,
  auth         text NOT NULL,
  user_agent   text,
  created_at   timestamp DEFAULT now(),
  last_used_at timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_staff ON push_subscriptions(staff_name);

-- Per-trigger notification on/off, so a specific trigger (in-app AND
-- push) can be muted from Admin Panel without a code change.
CREATE TABLE IF NOT EXISTS notification_trigger_settings (
  type         text PRIMARY KEY,
  label        text NOT NULL,
  enabled      text DEFAULT 'TRUE',
  updated_at   timestamp DEFAULT now()
);

INSERT INTO notification_trigger_settings (type, label) VALUES
  ('fleet_to_garage',        'Fleet to Garage'),
  ('low_stock',              'Low Stock'),
  ('car_out_for_service',    'Mid-Rental Car Sent to Garage'),
  ('car_back_from_service',  'Car Back from Garage'),
  ('reservation_reminder',   '24h Reservation Reminder'),
  ('unpaid_customer_job',    'Customer Job Unpaid 3+ Days')
ON CONFLICT (type) DO NOTHING;

-- Phone number for Staff and Driver config rows, so the rental agreement
-- can print full name + contact for both the checkout staff member and
-- any assigned driver.
ALTER TABLE config ADD COLUMN IF NOT EXISTS phone text;

-- Purchase Invoices (Garage invoice scanning, Phase 1 shell). Photo +
-- extracted line items, kept separate from Parts/Vendors until matching
-- logic exists (Phase 2+).
CREATE TABLE IF NOT EXISTS purchase_invoices (
  id                 text PRIMARY KEY,
  supplier_name      text,
  supplier_vendor_id text REFERENCES vendors(id) ON DELETE SET NULL,
  invoice_date       text,
  total_amount       numeric DEFAULT 0,
  photo_file_id      text REFERENCES files(id) ON DELETE SET NULL,
  work_order_id      text REFERENCES maintenance_log(id) ON DELETE SET NULL,
  customer_job_id    text REFERENCES customer_jobs(id) ON DELETE SET NULL,
  status             text DEFAULT 'Draft',
  scanned_by         text,
  created_at         timestamp DEFAULT now(),
  updated_at         timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_purchase_invoices_status ON purchase_invoices(status);
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_vendor ON purchase_invoices(supplier_vendor_id);

CREATE TABLE IF NOT EXISTS purchase_invoice_items (
  id             text PRIMARY KEY,
  invoice_id     text NOT NULL REFERENCES purchase_invoices(id) ON DELETE CASCADE,
  item_name      text NOT NULL,
  part_id        text REFERENCES parts(id) ON DELETE SET NULL,
  quantity       numeric DEFAULT 1,
  unit_price     numeric DEFAULT 0,
  line_total     numeric DEFAULT 0,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_purchase_invoice_items_invoice ON purchase_invoice_items(invoice_id);

-- Part cost history: logs every unit_cost change caused by confirming an
-- invoice scan, so price movement over time stays traceable.
CREATE TABLE IF NOT EXISTS part_cost_history (
  id                text PRIMARY KEY,
  part_id           text NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
  old_unit_cost     numeric,
  new_unit_cost     numeric NOT NULL,
  invoice_id        text REFERENCES purchase_invoices(id) ON DELETE SET NULL,
  changed_by        text,
  created_at        timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_part_cost_history_part ON part_cost_history(part_id, created_at DESC);

-- System health log: every periodic check (cron run, storage threshold,
-- etc.) logs itself here, success or failure.
CREATE TABLE IF NOT EXISTS system_health_log (
  id          text PRIMARY KEY,
  job_name    text NOT NULL,
  status      text NOT NULL,
  detail      text,
  created_at  timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_system_health_log_job ON system_health_log(job_name, created_at DESC);

-- Audit trail for notification trigger toggles: who last changed it, not
-- just when.
ALTER TABLE notification_trigger_settings ADD COLUMN IF NOT EXISTS updated_by text;

-- Drivers: promoted out of config.type='Driver' into a real table so it
-- can hold structured data (license/ID numbers, address) and documents
-- with expiry tracking. See PROJECT_NOTES.md for the migration reasoning.
CREATE TABLE IF NOT EXISTS drivers (
  id             text PRIMARY KEY,
  name           text NOT NULL,
  phone          text,
  license_number text,
  national_id    text,
  address        text,
  notes          text,
  active         text DEFAULT 'TRUE',
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_drivers_active ON drivers(active);

CREATE TABLE IF NOT EXISTS driver_documents (
  id             text PRIMARY KEY,
  driver_id      text NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  doc_type       text NOT NULL,
  label          text,
  file_id        text REFERENCES files(id) ON DELETE SET NULL,
  expiry_date    text,
  notes          text,
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_driver_documents_driver ON driver_documents(driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_documents_expiry ON driver_documents(expiry_date) WHERE expiry_date IS NOT NULL;

ALTER TABLE config ADD COLUMN IF NOT EXISTS receives_driver_document_reminders text DEFAULT 'FALSE';

INSERT INTO notification_trigger_settings (type, label, enabled)
VALUES ('driver_document_expiry', 'Driver Document Expiry', 'TRUE')
ON CONFLICT (type) DO NOTHING;

-- Drivers: own table (migrated off config.type='Driver' — see
-- PROJECT_NOTES.md). driver_documents holds license/ID/certificates with
-- optional expiry tracking, file stored via the existing files table.
CREATE TABLE IF NOT EXISTS drivers (
  id             text PRIMARY KEY,
  name           text NOT NULL,
  phone          text,
  license_number text,
  national_id    text,
  address        text,
  notes          text,
  active         text DEFAULT 'TRUE',
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_drivers_active ON drivers(active);

CREATE TABLE IF NOT EXISTS driver_documents (
  id             text PRIMARY KEY,
  driver_id      text NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
  doc_type       text NOT NULL,
  label          text,
  file_id        text REFERENCES files(id) ON DELETE SET NULL,
  expiry_date    text,
  notes          text,
  created_at     timestamp DEFAULT now(),
  updated_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_driver_documents_driver ON driver_documents(driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_documents_expiry ON driver_documents(expiry_date) WHERE expiry_date IS NOT NULL;

ALTER TABLE config ADD COLUMN IF NOT EXISTS receives_driver_document_reminders text DEFAULT 'FALSE';

INSERT INTO notification_trigger_settings (type, label, enabled)
VALUES ('driver_document_expiry', 'Driver Document Expiry', 'TRUE')
ON CONFLICT (type) DO NOTHING;

-- Per-staff permission to manage driver records/documents. Admin always
-- can (checked in code); this grants it to specific non-Admin staff.
ALTER TABLE config ADD COLUMN IF NOT EXISTS can_manage_drivers text DEFAULT 'FALSE';

-- Driver profile photo (headshot), distinct from Documents.
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS photo_file_id text REFERENCES files(id) ON DELETE SET NULL;

-- Plate rename history: lets a car's full History/Maintenance be found
-- under either its old or new plate. History rows keep their original
-- plate text unchanged (accurate to what happened); this table is the
-- resolution layer for cross-plate lookups.
CREATE TABLE IF NOT EXISTS plate_history (
  id          text PRIMARY KEY,
  old_plate   text NOT NULL,
  new_plate   text NOT NULL,
  changed_at  timestamp DEFAULT now(),
  changed_by  text
);

CREATE INDEX IF NOT EXISTS idx_plate_history_old ON plate_history(old_plate);
CREATE INDEX IF NOT EXISTS idx_plate_history_new ON plate_history(new_plate);

-- TIN No. field on driver profile.
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS tin_number text;

-- Driver TIN number (plain profile field, no reminder tracking).
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS tin_number text;

-- GPS tracker integration (TrackSolid Pro). One confirmed IMEI<->plate
-- pairing per row — deliberately human-confirmed (see writes.saveTrackerMatch),
-- never auto-written, since a wrong match would silently attribute one
-- car's movement to another car's plate.
CREATE TABLE IF NOT EXISTS vehicle_tracker_map (
  id            text PRIMARY KEY,
  plate         text NOT NULL UNIQUE,
  imei          text NOT NULL UNIQUE,
  device_name   text,
  confirmed_by  text,
  confirmed_at  timestamp DEFAULT now()
);

-- One row per car per day. distance_m is the totalMileage TrackSolid
-- already computes for us (meters) — stored as-is, converted to km only
-- for display, so raw source data stays intact.
CREATE TABLE IF NOT EXISTS vehicle_mileage_daily (
  id            text PRIMARY KEY,
  plate         text NOT NULL,
  imei          text NOT NULL,
  day           date NOT NULL,
  distance_m    numeric,
  trip_count    int,
  over_limit    boolean DEFAULT false,
  had_data      boolean DEFAULT true,
  synced_at     timestamp DEFAULT now(),
  UNIQUE(plate, day)
);

CREATE INDEX IF NOT EXISTS idx_vehicle_mileage_daily_day ON vehicle_mileage_daily(day);
CREATE INDEX IF NOT EXISTS idx_vehicle_mileage_daily_plate ON vehicle_mileage_daily(plate);

-- Trackers that exist on the TrackSolid account but aren't SmilesCars
-- fleet cars (test devices, other things sitting on the same account) —
-- dismissed once so they stop cluttering the "unmatched" review list on
-- every reload. Reversible: see writes.unignoreTrackerDevice.
CREATE TABLE IF NOT EXISTS ignored_tracker_devices (
  imei          text PRIMARY KEY,
  device_name   text,
  ignored_by    text,
  ignored_at    timestamp DEFAULT now()
);

-- Short-lived cache of TrackSolid's full device list. Fetching it live
-- means ~25+ signed API calls (root account + every client sub-account) —
-- fine occasionally, but the Tracking page was hitting TrackSolid's rate
-- limit ("request frequency too high") because every page reload repeated
-- that whole burst from scratch. getDeviceList() now serves from here
-- when the cache is fresh, and falls back to a stale cache (rather than
-- erroring) if TrackSolid is rate-limiting a refresh attempt.
CREATE TABLE IF NOT EXISTS tracksolid_device_cache (
  id          text PRIMARY KEY DEFAULT 'devices',
  payload     jsonb NOT NULL,
  fetched_at  timestamp DEFAULT now()
);
