-- ============================================================================
--  SmilesCars — Supabase schema for the API in /api + /lib
--  Run in the Supabase SQL editor (SQL Editor -> New query -> Run).
--
--  SAFE TO RE-RUN. Every statement is additive and idempotent:
--    * CREATE TABLE IF NOT EXISTS   — never touches a table that already exists
--    * ADD COLUMN IF NOT EXISTS     — never changes an existing column's type
--    * no DROP, no DELETE, no UPDATE of business data
--
--  It runs in three phases:
--    1. create any table that is missing
--    2. reconcile columns — every column the API touches, on every table, so a
--       table that arrived from the sheet export with a different set of
--       columns gets brought up to date
--    3. indexes
--
--  Column types are dictated by the API's write coercion (lib/core.js): a
--  column listed there as numeric/timestamp receives NULL when the app clears
--  it; everything else stays text so a blank "" is always a legal value.
--
--  Check the result with:  npm run db:check    (or GET /api?action=health)
-- ============================================================================


-- ============================================================================
--  PHASE 1 — tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS fleet (
  plate             text PRIMARY KEY,
  type              text,
  location          text,
  status            text,
  current_client    text,
  client_phone      text,
  booked_from       timestamp,
  return_date       timestamp,
  remarks           text,
  fuel_out          text,
  amount            numeric,
  currency          text,
  garage            text,
  payment_status    text,
  amount_paid       numeric,
  police_fine_out   numeric,
  parking_fine_out  numeric,
  km_out            text,
  driver            text,
  reg_card_url      text,
  photos_url        text,
  checked_out_by    text,
  booking_type      text
);

-- `id` gives the append-only log a stable newest-first order (the app used to
-- rely on sheet row position).
CREATE TABLE IF NOT EXISTS history (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp      timestamp,
  plate          text,
  type           text,
  action         text,
  client         text,
  client_phone   text,
  booked_from    timestamp,
  return_date    timestamp,
  location       text,
  remarks        text,
  staff_name     text,
  fuel_out       text,
  fuel_in        text,
  amount         numeric,
  currency       text,
  police_fine    numeric,
  parking_fine   text,
  garage         text,
  payment_status text,
  amount_paid    numeric,
  km_out         text,
  km_in          text,
  driver         text
);

-- Staff, locations, garages, drivers, fuel access.
CREATE TABLE IF NOT EXISTS config (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type     text,
  value    text,
  password text,
  role     text,
  active   text
);

CREATE TABLE IF NOT EXISTS settings (
  key   text PRIMARY KEY,
  value boolean
);

CREATE TABLE IF NOT EXISTS sold (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp  timestamp,
  plate      text,
  type       text,
  remarks    text,
  staff_name text
);

CREATE TABLE IF NOT EXISTS sub_hire (
  id                   text PRIMARY KEY,
  status               text,
  supplier_name        text,
  supplier_contact     text,
  vehicle_description  text,
  client               text,
  client_phone         text,
  booked_from          timestamp,
  return_date          timestamp,
  actual_return        timestamp,
  location             text,
  fuel_out             text,
  fuel_in              text,
  amount               numeric,
  currency             text,
  payment_status       text,
  amount_paid          numeric,
  supplier_amount      numeric,
  supplier_currency    text,
  supplier_pay_status  text,
  supplier_amount_paid numeric,
  police_fine          numeric,
  parking_fine         numeric,
  remarks              text,
  staff_name           text,
  timestamp            timestamp,
  plate_no             text
);

CREATE TABLE IF NOT EXISTS fuel (
  ref_no        text PRIMARY KEY,
  timestamp     timestamp,
  date          timestamp,
  plate         text,
  vehicle_type  text,
  product       text,
  amount_tsh    text,
  litres        text,
  authorised_by text,
  submitted_by  text,
  linked_client text,
  current_km    numeric
);

CREATE TABLE IF NOT EXISTS reservations (
  id           text PRIMARY KEY,
  plate        text,
  car_type     text,
  client_name  text,
  phone        text,
  pickup_date  timestamp,
  return_date  timestamp,
  pick_up_from text,
  remarks      text,
  staff_name   text,
  timestamp    timestamp
);

CREATE TABLE IF NOT EXISTS blacklist (
  id                text PRIMARY KEY,
  name              text,
  phone             text,
  license_no        text,
  license_image_url text,
  file_id           text,
  added_by          text,
  timestamp         timestamp
);

-- ── Tables that replace Google Drive / Script Properties ────────────────────

-- Licence photos, signatures, agreement PDFs and backups, served back to the
-- browser at /api?action=file&id=<id>.
CREATE TABLE IF NOT EXISTS files (
  id         text PRIMARY KEY,
  kind       text,            -- blacklist | signature | staff-signature | agreement | backup
  filename   text,
  mime_type  text,
  size_bytes integer,
  data       bytea NOT NULL,
  created_at timestamp,
  created_by text
);

-- Was: the "Agreements" sheet + a Drive folder.
CREATE TABLE IF NOT EXISTS agreements (
  ref        text,
  plate      text,
  client     text,
  staff_name text,
  timestamp  timestamp,
  drive_url  text,           -- kept as the column name so pre-migration rows still read
  file_id    text
);

-- Client signature hand-off. Was: Script Properties, 24h TTL.
CREATE TABLE IF NOT EXISTS signature_tokens (
  token      text PRIMARY KEY,
  file_id    text,
  url        text,
  created_at timestamp
);

-- One per staff member. Was: Script Properties.
CREATE TABLE IF NOT EXISTS staff_signatures (
  staff_name text PRIMARY KEY,   -- stored lowercased
  file_id    text,
  url        text,
  updated_at timestamp
);

-- Was: the "ExportLog" sheet.
CREATE TABLE IF NOT EXISTS export_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp   timestamp,
  staff_name  text,
  role        text,
  export_type text,
  row_count   integer,
  filters     text
);


-- ============================================================================
--  PHASE 2 — column reconciliation
--
--  Every column the API reads or writes, for every table. A table created
--  above already has them all and each statement is a no-op; a table that came
--  from the sheet export gets whatever it is missing. Types are never altered,
--  so an existing column keeps whatever type it already has.
-- ============================================================================

-- ── Renames first ───────────────────────────────────────────────────────────
-- The Agreements sheet headed this column "Staff" (History used "Staff Name"),
-- so the export produced `staff`. Rename rather than add, or the staff names on
-- existing agreement rows are stranded in a column nothing reads.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='agreements' AND column_name='staff')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='agreements' AND column_name='staff_name')
  THEN
    ALTER TABLE agreements RENAME COLUMN staff TO staff_name;
  END IF;
END $$;

-- ── Surrogate keys ──────────────────────────────────────────────────────────
-- On a non-empty table Postgres backfills an identity column in the table's
-- existing physical order, which for an append-only log is insertion order.
ALTER TABLE history ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE config  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE sold    ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- ── Fleet ───────────────────────────────────────────────────────────────────
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS plate            text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS type             text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS location         text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS status           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS current_client   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS client_phone     text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS booked_from      timestamp;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS return_date      timestamp;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS remarks          text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS fuel_out         text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS amount           numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS currency         text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS garage           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS payment_status   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS amount_paid      numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS police_fine_out  numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS parking_fine_out numeric;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS km_out           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS driver           text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS reg_card_url     text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS photos_url       text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS checked_out_by   text;
ALTER TABLE fleet ADD COLUMN IF NOT EXISTS booking_type     text;

-- ── History ─────────────────────────────────────────────────────────────────
ALTER TABLE history ADD COLUMN IF NOT EXISTS timestamp      timestamp;
ALTER TABLE history ADD COLUMN IF NOT EXISTS plate          text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS type           text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS action         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS client         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS client_phone   text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS booked_from    timestamp;
ALTER TABLE history ADD COLUMN IF NOT EXISTS return_date    timestamp;
ALTER TABLE history ADD COLUMN IF NOT EXISTS location       text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS remarks        text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS staff_name     text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS fuel_out       text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS fuel_in        text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS amount         numeric;
ALTER TABLE history ADD COLUMN IF NOT EXISTS currency       text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS police_fine    numeric;
ALTER TABLE history ADD COLUMN IF NOT EXISTS parking_fine   text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS garage         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS payment_status text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS amount_paid    numeric;
ALTER TABLE history ADD COLUMN IF NOT EXISTS km_out         text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS km_in          text;
ALTER TABLE history ADD COLUMN IF NOT EXISTS driver         text;

-- ── Config ──────────────────────────────────────────────────────────────────
ALTER TABLE config ADD COLUMN IF NOT EXISTS type     text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS value    text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS password text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS role     text;
ALTER TABLE config ADD COLUMN IF NOT EXISTS active   text;

-- ── Settings ────────────────────────────────────────────────────────────────
ALTER TABLE settings ADD COLUMN IF NOT EXISTS key   text;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS value boolean;

-- ── Sold ────────────────────────────────────────────────────────────────────
ALTER TABLE sold ADD COLUMN IF NOT EXISTS timestamp  timestamp;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS plate      text;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS type       text;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS remarks    text;
ALTER TABLE sold ADD COLUMN IF NOT EXISTS staff_name text;

-- ── Sub-Hire ────────────────────────────────────────────────────────────────
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS id                   text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS status               text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_name        text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_contact     text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS vehicle_description  text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS client               text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS client_phone         text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS booked_from          timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS return_date          timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS actual_return        timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS location             text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS fuel_out             text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS fuel_in              text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS amount               numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS currency             text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS payment_status       text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS amount_paid          numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_amount      numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_currency    text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_pay_status  text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS supplier_amount_paid numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS police_fine          numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS parking_fine         numeric;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS remarks              text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS staff_name           text;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS timestamp            timestamp;
ALTER TABLE sub_hire ADD COLUMN IF NOT EXISTS plate_no             text;

-- ── Fuel ────────────────────────────────────────────────────────────────────
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS ref_no        text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS timestamp     timestamp;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS date          timestamp;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS plate         text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS vehicle_type  text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS product       text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS amount_tsh    text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS litres        text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS authorised_by text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS submitted_by  text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS linked_client text;
ALTER TABLE fuel ADD COLUMN IF NOT EXISTS current_km    numeric;

-- ── Reservations ────────────────────────────────────────────────────────────
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS id           text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS plate        text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS car_type     text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS client_name  text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS phone        text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS pickup_date  timestamp;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS return_date  timestamp;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS pick_up_from text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS remarks      text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS staff_name   text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS timestamp    timestamp;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS booking_type  text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS drop_off_to   text;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS transfer_date timestamp;
UPDATE reservations SET booking_type = 'Rental' WHERE booking_type IS NULL;

-- ── Blacklist ───────────────────────────────────────────────────────────────
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS id                text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS name              text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS phone             text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS license_no        text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS license_image_url text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS file_id           text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS added_by          text;
ALTER TABLE blacklist ADD COLUMN IF NOT EXISTS timestamp         timestamp;

-- ── Files ───────────────────────────────────────────────────────────────────
ALTER TABLE files ADD COLUMN IF NOT EXISTS id         text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS kind       text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS filename   text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS mime_type  text;
ALTER TABLE files ADD COLUMN IF NOT EXISTS size_bytes integer;
ALTER TABLE files ADD COLUMN IF NOT EXISTS data       bytea;
ALTER TABLE files ADD COLUMN IF NOT EXISTS created_at timestamp;
ALTER TABLE files ADD COLUMN IF NOT EXISTS created_by text;

-- ── Agreements ──────────────────────────────────────────────────────────────
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS ref        text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS plate      text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS client     text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS staff_name text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS timestamp  timestamp;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS drive_url  text;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS file_id    text;

-- ── Signature tokens ────────────────────────────────────────────────────────
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS token      text;
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS file_id    text;
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS url        text;
ALTER TABLE signature_tokens ADD COLUMN IF NOT EXISTS created_at timestamp;

-- ── Staff signatures ────────────────────────────────────────────────────────
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS staff_name text;
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS file_id    text;
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS url        text;
ALTER TABLE staff_signatures ADD COLUMN IF NOT EXISTS updated_at timestamp;

-- ── Export log ──────────────────────────────────────────────────────────────
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS timestamp   timestamp;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS staff_name  text;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS role        text;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS export_type text;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS row_count   integer;
ALTER TABLE export_log ADD COLUMN IF NOT EXISTS filters     text;

-- Blank counts as active in code; this just makes it explicit.
UPDATE config SET active = 'TRUE' WHERE type = 'Staff' AND (active IS NULL OR active = '');


-- ============================================================================
--  PHASE 3 — indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS history_plate_idx      ON history (lower(btrim(plate)));
CREATE INDEX IF NOT EXISTS history_staff_name_idx ON history (lower(btrim(staff_name)));
CREATE INDEX IF NOT EXISTS fuel_plate_idx         ON fuel (lower(btrim(plate)));
CREATE INDEX IF NOT EXISTS files_kind_idx         ON files (kind);
CREATE INDEX IF NOT EXISTS agreements_ref_idx     ON agreements (ref);

-- ============================================================================
--  Leads / Maintenance module additions
-- ============================================================================

CREATE TABLE IF NOT EXISTS maintenance_log (
  id                text PRIMARY KEY,
  plate             text NOT NULL,
  opened_by         text,
  assigned_mechanic text,
  issue_description text,
  status            text DEFAULT 'Queued',
  date_opened       timestamp DEFAULT now(),
  date_closed       timestamp,
  odometer          text,
  parts_cost        numeric DEFAULT 0,
  labor_cost        numeric DEFAULT 0,
  total_cost        numeric DEFAULT 0,
  notes             text,
  created_at        timestamp DEFAULT now(),
  updated_at        timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_log_plate  ON maintenance_log(plate);
CREATE INDEX IF NOT EXISTS idx_maintenance_log_status ON maintenance_log(status);

-- Human-facing sequential reference number, e.g. SC/GAR/2026/08/0001.
-- id stays as the internal PK (MX-XXXXXXXX); ref_no is what staff see/write down.
ALTER TABLE maintenance_log ADD COLUMN IF NOT EXISTS ref_no text UNIQUE;

-- Job card line items — one row per part, linked to a work order.
-- No labor field: line items ARE the cost breakdown (labor isn't tracked).
CREATE TABLE IF NOT EXISTS maintenance_items (
  id             text PRIMARY KEY,
  work_order_id  text NOT NULL REFERENCES maintenance_log(id) ON DELETE CASCADE,
  item_name      text NOT NULL,
  quantity       numeric DEFAULT 1,
  unit_cost      numeric DEFAULT 0,
  line_total     numeric DEFAULT 0,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_items_wo ON maintenance_items(work_order_id);

-- Running update log for a work order (timestamped entries, not a single
-- overwritable notes field) — visible history of everything reported as
-- the job progressed.
CREATE TABLE IF NOT EXISTS maintenance_updates (
  id             text PRIMARY KEY,
  work_order_id  text NOT NULL REFERENCES maintenance_log(id) ON DELETE CASCADE,
  author         text,
  message        text NOT NULL,
  created_at     timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_updates_wo ON maintenance_updates(work_order_id);
